name: Rust Format Check

on:
  pull_request:
    branches: [ main ] # Specify the branch you want to trigger the workflow on
  push:
    branches: [ main ] # Specify the branch you want to trigger the workflow on

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format Check
        run: cargo fmt
