name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Wait for database to be ready
      run: sleep 10s
    - name: Get DB URL
      id: db_url
      run: echo "DATABASE_URL=postgres://postgres:1234@localhost:5432/postgres" >> "$GITHUB_ENV"
    - name: Fill Database with columns
      run: psql -h localhost -U postgres -d postgres -f db/sqlx/migrations
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
