name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Wait for database to be ready
      run: sleep 10s
    - name: Install pgMigrate
      run: |
        curl -L https://github.com/robinjmurphy/pgmigrate/releases/download/vX.X.X/pgmigrate-linux-amd64-X.X.X.tar.gz | tar xz
        sudo mv pgmigrate /usr/local/bin/
    - name: Run migration
      env:
        PGPASSWORD: 1234
      run: pgmigrate migrate -dir /db/sqlx/migrations -dsn "postgres://postgres:1234@localhost:5432/postgres"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
