name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: db_url
    - name: Set Database URL Env Variable
      run: echo "DATABASE_URL=$(cat db_url/url)" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
