name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Wait for database to be ready
      run: sleep 10s
    - name: Set DATABASE_URL in ENV
      run: echo "DATABASE_URL=postgres://postgres:1234@localhost:5432/postgres" >> "$GITHUB_ENV"
    - name: Run migration
      env:
        PGPASSWORD: 1234
      run: chmod +x scripts/__test-utils__/ci_migrations.sh && scripts/__test-utils__/ci_migrations.sh
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt
    - name: Run quick tests
      run: cargo test --verbose
    - name: Run slow tests
      run: cargo test --verbose -- --ignored
    - name: Run clippy
      run: cargo clippy
